### ISSUE TITLE
ImportError: No module named continues

### ISSUE THREAD

**Issue by chr1s0x1** [0x36/ghidra_kernelcache#11]
I placed the .py files in my ghidra_scripts folder in: /user/user_name/ghidra_scripts.

After doing so, I went checked KC.py in the script manager and ran it, just to get this error:

Traceback (most recent call last):
  File "/Users/chr1s0x1/ghidra_scripts/KC.py", line 6, in <module>
    from utils.helpers import *
  File "/Users/chr1s0x1/ghidra_scripts/utils/helpers.py", line 17, in <module>
    from  generic.continues import RethrowContinuesFactory
ImportError: No module named continues

Any reason as to why this happens? Thanks

**Comment by TylerJaacks** [comment]
I have this issue as well.

**Comment by TylerJaacks** [comment]
I commented out line 17 in utils/helper.py and I think that fixed it.
