### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getName'

### ISSUE THREAD

**Issue by docfate111** [0x36/ghidra_kernelcache#8]
```
 kc.process_kernel_kext()
[+] Processing IOPMinformee class with vtab=0xfffffe00071eb418
Traceback (most recent call last):
  File "python", line 1, in <module>
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/kext.py", line 76, in process_kernel_kext
    self.process_all_classes()
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/kext.py", line 125, in process_all_classes
    kernelCacheClass(self.objects[name],False,self.macOS)
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 391, in __init__
    self.defineObjects()
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 443, in defineObjects
    self._defineVtable()
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 484, in _defineVtable
    funcDef = self.prepareSignature(method)
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 566, in prepareSignature
    return self.parseCSignature(method)
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 647, in parseCSignature
    df = self.setCustomFunctionDefinition(methName,methAddr,namespace,text)
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/ios_kc.py", line 496, in setCustomFunctionDefinition
    func = fixLabel(addr)
  File "/Users/thelshell/hacking/ghidra_kernelcache/utils/helpers.py", line 284, in fixLabel
    name = getSymbolAt(data).getName()
AttributeError: 'NoneType' object has no attribute 'getName'
 ```
 I did the steps below on MacOS 11.6 but with binaries someone sent from 12.1.

Did this: Create a new folder in your Ghidra project, then load System/Library/Kernels/kernel.release.XXXXX into that folder and let Ghidra analyzes it.
Did this: Create a new Project Archive : Go to DataType Provider → Click on the arrow in the top right of the window → New Project Archive → Place it inside the newly created Folder → Name it to something (i.e macOS_12.1).
Ran this command
$ iometa -n -A /System/Library/Kernels/kernel.release.t8101 > kernel.txt
then ran all the commands.
iometa is compiled for x86_64 is that the issue?
It made the kernel.txt fine though.

**Comment by docfate111** [comment]
never mind i just needed to run the script from ghidra script manager and wait a while
